### ISSUE TITLE
ROS auf Arch

### ISSUE THREAD

**Issue by IliHanSoLow** [The-Pipeman-Organization/rosbot#1]
hat jemand es Geschaft ROS auf Arch zu nutzen?
Wenn ja wie?
Danke

**Comment by snaens** [comment]
Probiers hiermit mal aus:
[https://wiki.archlinux.org/title/ROS](url)   

und les dir auch das durch
[https://wiki.ros.org/Installation/Arch](url)


---
Wenn das nicht geht / nicht erwünscht ist, kann man es selber kompilieren:
[https://wiki.ros.org/Installation/Source](url)

---
viel erfolg!

**Comment by MrRedRhino** [comment]
Cringe

**Comment by IliHanSoLow** [comment]
nichts hat funktioniert xD

**Comment by snaens** [comment]
und genau deshalb ueberlegen wir uns unser eignenes "ROS" herzustellen.
ROS ist halt total doof gemacht
